[CmdletBinding()]
param(
    [string] $HeaderPath,
    [switch] $AcquireHeader,
    [switch] $Verify
)

. (Join-Path $PSScriptRoot 'common.ps1')
$root = Get-RepositoryRoot
$manifestPath = Join-Path $root 'compatibility\m1-binding-subset.json'
$manifest = Get-Content -Raw -LiteralPath $manifestPath | ConvertFrom-Json

if ($AcquireHeader) {
    if (-not $HeaderPath) {
        $HeaderPath = Join-Path $root '.cache\m1\migraphx.h'
    }
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $HeaderPath) | Out-Null
    Invoke-WebRequest -Uri $manifest.source.headerUrl -OutFile $HeaderPath
}

if (-not $HeaderPath) {
    throw 'Specify -HeaderPath or use -AcquireHeader.'
}
$HeaderPath = (Resolve-Path -LiteralPath $HeaderPath).Path
$actualHash = (Get-FileHash -Algorithm SHA256 -LiteralPath $HeaderPath).Hash.ToLowerInvariant()
if ($actualHash -ne $manifest.source.headerSha256) {
    throw "Frozen header SHA-256 mismatch. Expected $($manifest.source.headerSha256), got $actualHash."
}
if ((Get-Item -LiteralPath $HeaderPath).Length -ne $manifest.source.headerByteLength) {
    throw 'Frozen header byte length does not match the manifest.'
}

function Normalize-CDeclaration([string] $value) {
    return ([regex]::Replace($value, '\s+', ' ')).Trim()
}

$normalizedHeader = Normalize-CDeclaration (Get-Content -Raw -LiteralPath $HeaderPath)
foreach ($handle in $manifest.handles) {
    if (-not $normalizedHeader.Contains((Normalize-CDeclaration $handle.cDeclaration))) {
        throw "Handle declaration is absent from the frozen header: $($handle.cDeclaration)"
    }
}
foreach ($function in $manifest.functions) {
    if (-not $normalizedHeader.Contains((Normalize-CDeclaration $function.cDeclaration))) {
        throw "Function declaration is absent from the frozen header: $($function.cDeclaration)"
    }
}

$banner = @"
// <auto-generated />
// Source: compatibility/m1-binding-subset.json
// Frozen migraphx.h SHA-256: $($manifest.source.headerSha256)
// Regenerate with eng/generate-interop.ps1; do not edit by hand.
"@

$common = [Text.StringBuilder]::new()
[void]$common.AppendLine($banner)
[void]$common.AppendLine('using System;')
[void]$common.AppendLine()
[void]$common.AppendLine('namespace JYPPX.ROCm.MIGraphXSharp.Interop;')
[void]$common.AppendLine()
[void]$common.AppendLine('internal enum NativeMIGraphXStatus')
[void]$common.AppendLine('{')
foreach ($value in $manifest.enums[0].values) {
    [void]$common.AppendLine("    $($value.managedName) = $($value.value),")
}
[void]$common.AppendLine('}')
[void]$common.AppendLine()
[void]$common.AppendLine('internal static partial class NativeMethods')
[void]$common.AppendLine('{')
[void]$common.AppendLine("    internal const string LibraryName = `"$($manifest.nativeLibrary.logicalName)`";")
[void]$common.AppendLine('}')

function Get-ManagedParameters($function) {
    $parts = foreach ($parameter in $function.parameters) {
        $modifierProperty = $parameter.PSObject.Properties['managedModifier']
        $modifier = if ($null -ne $modifierProperty) { "$($modifierProperty.Value) " } else { '' }
        "$modifier$($parameter.managedType) $($parameter.cName)"
    }
    return $parts -join ', '
}

$libraryImport = [Text.StringBuilder]::new()
[void]$libraryImport.AppendLine($banner)
[void]$libraryImport.AppendLine('#if MIGRAPHX_LIBRARYIMPORT_PATH')
[void]$libraryImport.AppendLine('using System;')
[void]$libraryImport.AppendLine('using System.Runtime.CompilerServices;')
[void]$libraryImport.AppendLine('using System.Runtime.InteropServices;')
[void]$libraryImport.AppendLine()
[void]$libraryImport.AppendLine('namespace JYPPX.ROCm.MIGraphXSharp.Interop;')
[void]$libraryImport.AppendLine()
[void]$libraryImport.AppendLine('internal static partial class NativeMethods')
[void]$libraryImport.AppendLine('{')
foreach ($function in $manifest.functions) {
    [void]$libraryImport.AppendLine("    [LibraryImport(LibraryName, EntryPoint = `"$($function.cName)`")]")
    [void]$libraryImport.AppendLine('    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]')
    [void]$libraryImport.AppendLine("    internal static partial NativeMIGraphXStatus $($function.managedName)($(Get-ManagedParameters $function));")
    [void]$libraryImport.AppendLine()
}
[void]$libraryImport.AppendLine('}')
[void]$libraryImport.AppendLine('#endif')

$dllImport = [Text.StringBuilder]::new()
[void]$dllImport.AppendLine($banner)
[void]$dllImport.AppendLine('#if MIGRAPHX_DLLIMPORT_PATH')
[void]$dllImport.AppendLine('using System;')
[void]$dllImport.AppendLine('using System.Runtime.InteropServices;')
[void]$dllImport.AppendLine()
[void]$dllImport.AppendLine('namespace JYPPX.ROCm.MIGraphXSharp.Interop;')
[void]$dllImport.AppendLine()
[void]$dllImport.AppendLine('internal static partial class NativeMethods')
[void]$dllImport.AppendLine('{')
foreach ($function in $manifest.functions) {
    [void]$dllImport.AppendLine("    [DllImport(LibraryName, EntryPoint = `"$($function.cName)`", CallingConvention = CallingConvention.Cdecl)]")
    [void]$dllImport.AppendLine("    internal static extern NativeMIGraphXStatus $($function.managedName)($(Get-ManagedParameters $function));")
    [void]$dllImport.AppendLine()
}
[void]$dllImport.AppendLine('}')
[void]$dllImport.AppendLine('#endif')

$outputs = [ordered]@{
    'NativeMethods.g.cs' = $common.ToString()
    'NativeMethods.LibraryImport.g.cs' = $libraryImport.ToString()
    'NativeMethods.DllImport.g.cs' = $dllImport.ToString()
}
$generatedDirectory = Join-Path $root 'src\JYPPX.ROCm.MIGraphX.CSharp.API\Generated'

foreach ($entry in $outputs.GetEnumerator()) {
    $path = Join-Path $generatedDirectory $entry.Key
    $expected = $entry.Value.Replace("`r`n", "`n")
    if ($Verify) {
        if (-not (Test-Path -LiteralPath $path)) {
            throw "Generated output is missing: $path"
        }
        $actual = (Get-Content -Raw -LiteralPath $path).Replace("`r`n", "`n")
        if ($actual -ne $expected) {
            throw "Generated output drifted: $path"
        }
    }
    else {
        [IO.File]::WriteAllText($path, $expected, [Text.UTF8Encoding]::new($false))
    }
}

Write-Output "M1 interop generation $($(if ($Verify) { 'verification' } else { 'update' })) passed for $actualHash."
