<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>JYPPX.ROCm.MIGraphXSharp.BindingGenerator</AssemblyName>
    <RootNamespace>JYPPX.ROCm.MIGraphXSharp.BindingGenerator</RootNamespace>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
</Project>
