<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <MIGraphXConsumerVersion Condition="'$(MIGraphXConsumerVersion)' == ''">0.0.0</MIGraphXConsumerVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="JYPPX.ROCm.MIGraphX.CSharp.API.HIP.Interop" Version="$(MIGraphXConsumerVersion)" />
  </ItemGroup>
</Project>
